services:
  health:
    image: burenotti/health:latest
    command: [ "-m", "health", "--config", "/project/config/config.compose.yaml" ]
    build:
      dockerfile: Dockerfile
      context: '.'
    volumes:
      - .:/project/
    networks:
      - database
    ports:
      - 80:8080
    expose:
      - 80

  postgres:
    image: postgres:16
    networks:
      - database
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
    env_file:
      - docker/postgres.env

volumes:
  pg_data:

networks:
  database:
